import type { AppData } from './types';
import { defaultAtsSettings, defaultResumeSettings } from './features/admin/components/tabs/resume/defaultSettings';

export const fallbackData: AppData = {
  profile: {
    id: 1,
    fullName: 'Asil Al-Aziz Al-Rumaili',
    fullNameAr: 'أصيل العزي محمد الرميلي',
    firstName: 'Asil',
    firstNameAr: 'أصيل',
    middleName: 'Al-Aziz',
    middleNameAr: 'العزيز',
    lastName: 'Al-Rumaili',
    lastNameAr: 'الرميلي',
    jobTitle: 'Graphic Designer',
    jobTitleAr: 'مصمم جرافيك',
    bio: 'Crafting visual identities that communicate, inspire, and endure.',
    bioAr: 'أبتكر هويات بصرية تواصل وتلهم وتدوم.',
    photoUrl: '',
    email: '',
    location: 'Riyadh, KSA',
    locationAr: 'الرياض، المملكة العربية السعودية',
    heroEffect: 'Parallax' as const,
    themeColor: '#c9a84c',
    statsProjects: 0,
    statsExperience: 0,
    statsClients: 0,
    statsAwards: 0,
  },
  socialLinks: [],
  skills: [],
  experience: [],
  education: [],
  certifications: [],
  projects: [],
  blogPosts: [],
  testimonials: [],
  reviews: [],
  settings: {},
  resumeVersions: [
    {
      id: 'ats-default',
      name: 'Default ATS Resume',
      type: 'ats',
      settings: { ...defaultAtsSettings, sections: [...defaultAtsSettings.sections] },
      isDefault: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'regular-default',
      name: 'Default Regular Resume',
      type: 'regular',
      settings: { ...defaultResumeSettings, sections: [...defaultResumeSettings.sections] },
      isDefault: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
};
